// Package v2rayxhttp implements the client-side XHTTP stream-one transport
// used by VLESS profiles generated by Xray and Mihomo.
//
// The request framing follows MetaCubeX/mihomo's GPL-3.0-or-later XHTTP
// implementation while using sing-box's dialer and TLS abstractions.
package v2rayxhttp

import (
	"context"
	cryptorand "crypto/rand"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/sagernet/sing-box/adapter"
	"github.com/sagernet/sing-box/common/tls"
	"github.com/sagernet/sing-box/option"
	"github.com/sagernet/sing-box/transport/v2rayhttp"
	E "github.com/sagernet/sing/common/exceptions"
	M "github.com/sagernet/sing/common/metadata"
	N "github.com/sagernet/sing/common/network"
	sHTTP "github.com/sagernet/sing/protocol/http"

	"golang.org/x/net/http2"
)

const (
	defaultPaddingRange = "100-1000"
)

var _ adapter.V2RayClientTransport = (*Client)(nil)

type Client struct {
	transport  http.RoundTripper
	requestURL url.URL
	host       string
	headers    http.Header
	noGRPC     bool
	paddingMin int
	paddingMax int
}

func NewClient(
	ctx context.Context,
	dialer N.Dialer,
	serverAddr M.Socksaddr,
	options option.V2RayXHTTPOptions,
	tlsConfig tls.Config,
) (adapter.V2RayClientTransport, error) {
	if tlsConfig == nil {
		return nil, E.New("XHTTP requires TLS")
	}
	switch options.Mode {
	case "", "auto", "stream-one":
	default:
		return nil, E.New("XHTTP mode ", options.Mode, " is not supported by this client build")
	}

	paddingMin, paddingMax, err := parseRange(options.XPaddingBytes, defaultPaddingRange)
	if err != nil {
		return nil, E.Cause(err, "parse XHTTP padding")
	}

	host := strings.TrimSpace(options.Host)
	if host == "" {
		host = serverAddr.String()
	}
	requestURL := url.URL{
		Scheme: "https",
		Host:   host,
	}
	if err := sHTTP.URLSetPath(&requestURL, options.Path); err != nil {
		return nil, E.Cause(err, "parse XHTTP path")
	}
	if requestURL.Path == "" {
		requestURL.Path = "/"
	} else if !strings.HasPrefix(requestURL.Path, "/") {
		requestURL.Path = "/" + requestURL.Path
	}
	if !strings.HasSuffix(requestURL.Path, "/") {
		requestURL.Path += "/"
	}

	var transport http.RoundTripper
	if nextProtos := tlsConfig.NextProtos(); len(nextProtos) == 1 && nextProtos[0] == "h3" {
		transport, err = newHTTP3Transport(ctx, dialer, serverAddr, tlsConfig, time.Duration(options.KeepAlivePeriod))
	} else {
		clientTLS := tlsConfig.Clone()
		clientTLS.SetNextProtos([]string{http2.NextProtoTLS})
		tlsDialer := tls.NewDialer(dialer, clientTLS)
		transport = &http2.Transport{
			ReadIdleTimeout: time.Duration(options.KeepAlivePeriod),
			PingTimeout:     time.Duration(options.PingTimeout),
			DialTLSContext: func(ctx context.Context, network, addr string, _ *tls.STDConfig) (net.Conn, error) {
				return tlsDialer.DialTLSContext(ctx, serverAddr)
			},
		}
	}
	if err != nil {
		return nil, err
	}

	return &Client{
		transport:  transport,
		requestURL: requestURL,
		host:       host,
		headers:    options.Headers.Build(),
		noGRPC:     options.NoGRPCHeader,
		paddingMin: paddingMin,
		paddingMax: paddingMax,
	}, nil
}

func (c *Client) DialContext(ctx context.Context) (net.Conn, error) {
	pipeReader, pipeWriter := io.Pipe()
	request := &http.Request{
		Method: http.MethodPost,
		Body:   pipeReader,
		URL:    cloneURL(c.requestURL),
		Header: c.headers.Clone(),
		Host:   c.host,
	}
	request = request.WithContext(ctx)
	if request.Header.Get("User-Agent") == "" {
		request.Header.Set("User-Agent", "Mozilla/5.0")
	}
	if request.Header.Get("Accept") == "" {
		request.Header.Set("Accept", "*/*")
	}
	if request.Header.Get("Accept-Language") == "" {
		request.Header.Set("Accept-Language", "en-US,en;q=0.9")
	}
	if request.Header.Get("Cache-Control") == "" {
		request.Header.Set("Cache-Control", "no-cache")
	}
	if request.Header.Get("Pragma") == "" {
		request.Header.Set("Pragma", "no-cache")
	}
	if !c.noGRPC {
		request.Header.Set("Content-Type", "application/grpc")
	}
	paddingLength, err := randomBetween(c.paddingMin, c.paddingMax)
	if err != nil {
		_ = pipeReader.Close()
		_ = pipeWriter.Close()
		return nil, err
	}
	referer := cloneURL(c.requestURL)
	query := referer.Query()
	query.Set("x_padding", strings.Repeat("X", paddingLength))
	referer.RawQuery = query.Encode()
	request.Header.Set("Referer", referer.String())

	conn := v2rayhttp.NewLateHTTPConn(pipeWriter)
	go func() {
		response, roundTripErr := c.transport.RoundTrip(request)
		if roundTripErr != nil {
			_ = pipeReader.CloseWithError(roundTripErr)
			_ = pipeWriter.CloseWithError(roundTripErr)
			conn.Setup(nil, roundTripErr)
			return
		}
		if response.StatusCode < 200 || response.StatusCode >= 300 {
			statusErr := E.New("XHTTP stream-one unexpected status: ", response.Status)
			_ = response.Body.Close()
			_ = pipeReader.CloseWithError(statusErr)
			_ = pipeWriter.CloseWithError(statusErr)
			conn.Setup(nil, statusErr)
			return
		}
		conn.Setup(response.Body, nil)
	}()
	return conn, nil
}

func (c *Client) Close() error {
	switch transport := c.transport.(type) {
	case interface{ Close() error }:
		return transport.Close()
	case interface{ CloseIdleConnections() }:
		transport.CloseIdleConnections()
	}
	return nil
}

func cloneURL(source url.URL) *url.URL {
	cloned := source
	return &cloned
}

func parseRange(value, fallback string) (int, int, error) {
	if strings.TrimSpace(value) == "" {
		value = fallback
	}
	parts := strings.Split(strings.TrimSpace(value), "-")
	if len(parts) < 1 || len(parts) > 2 {
		return 0, 0, fmt.Errorf("invalid range %q", value)
	}
	minimum, err := strconv.Atoi(strings.TrimSpace(parts[0]))
	if err != nil {
		return 0, 0, fmt.Errorf("invalid range %q", value)
	}
	maximum := minimum
	if len(parts) == 2 {
		maximum, err = strconv.Atoi(strings.TrimSpace(parts[1]))
		if err != nil {
			return 0, 0, fmt.Errorf("invalid range %q", value)
		}
	}
	if minimum < 0 || maximum < minimum {
		return 0, 0, fmt.Errorf("invalid range %q", value)
	}
	return minimum, maximum, nil
}

func randomBetween(minimum, maximum int) (int, error) {
	if minimum == maximum {
		return minimum, nil
	}
	value, err := cryptorand.Int(cryptorand.Reader, big.NewInt(int64(maximum-minimum+1)))
	if err != nil {
		return 0, err
	}
	return minimum + int(value.Int64()), nil
}
